# Generated by Django 5.2.8 on 2025-12-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=False)),
                ('show_to', models.CharField(choices=[('nobody', 'هیچکس'), ('closefriends', 'دوستان صمیمی'), ('all', 'همه')], default='nobody', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('social', 'اجتماعی'), ('sport', 'ورزشی')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_pictures/20251217')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست',
            },
        ),
    ]
