# Generated by Django 5.2.8 on 2025-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('birthdate', models.DateField(null=True)),
                ('bio', models.TextField(null=True)),
                ('city', models.CharField(choices=[('tehran', 'تهران'), ('isfahan', 'اصهان')], default='isfahan', max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
