# Generated by Django 5.2.8 on 2025-11-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('social', 'اجتماعی'), ('sport', 'ورزشی')], default='sport', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='close_friend',
            field=models.ManyToManyField(blank=True, null=True, to='core.user'),
        ),
    ]
